name = "homepage"
compatibility_date = "2024-05-02"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output"

main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"
